apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-gitops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lilerick/gitops-practica.git
    targetRevision: main
    path: webapp

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
